# docker-compose configuration for core-platform project

version: "3.9"
services:
  core-platform:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: squares_admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: core_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
